export const ERROR_TAGS = {
  LANGCHAIN_ERROR: "LANGCHAIN_ERROR ",
  LANGCHAIN_CHUNKING_ERROR: "LANGCHAIN_CHUNKING_ERROR ",
  LANGCHAIN_SPLIT_ERROR: "LANGCHAIN_SPLIT_ERROR ",
  OPENAI_API_ERROR: "OPENAI_API_ERROR ",
  VECTOR_DB_ERROR: "VECTOR_DB_ERROR ",
  FILE_READ_ERROR: "FILE_READ_ERROR ",
  ENV_CONFIG_ERROR: "ENV_CONFIG_ERROR ",
  API_REQUEST_ERROR: "API_REQUEST_ERROR ",
  INPUT_VALIDATION_ERROR: "INPUT_VALIDATION_ERROR ",
} as const;

export type ErrorTag = keyof typeof ERROR_TAGS;
